sudo: required
services:
  - docker

before_install:
  - docker build -t mridhu/docker-nodeapp -f Dockerfile .

script:
  - docker run mridhu/docker-nodeapp:latest -- --coverage
<<<<<<< HEAD
=======
=======
  - docker images 

after_success:
  - docker --version
  access_key_id: $AWS_access_KEY
  secret_access_key: "$AWS_SECRET_KEY" 
    secure: "$AWS_SECRET_KEY"
  - pip install awscli
  - eval $(aws ecr get-login --region us-east-1)
  - docker tag mridhu/docker-nodeapp:latest 528111971566.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest
  - docker push 528111971566.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest

>>>>>>> 44716c1... testing travis
>>>>>>> e7adbcc... travis
 
